### ISSUE TITLE
Set up basic website using Jekyll

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#1]
Similar to http://cameratraps.inbo.be

**Comment by stijnvanhoey** [comment]
some theme options to try out:
* https://github.com/DevTips/Artists-Theme
* https://mmistakes.github.io/so-simple-theme/
* http://t413.com/SinglePaged/

**Comment by peterdesmet** [comment]
Please move all website content to /docs

**Comment by niconoe** [comment]
I did the move but then get Jekyll failure error messages... Since I don't have access to the repository settings, is GitHub pages (auto)publishing in place? If so, maybe you need to change the settings so the site content is loaded from the `docs` subdirectory, as explained [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)?

Anyway, sorry for breaking things at first commit 🥇

**Comment by peterdesmet** [comment]
@niconoe Thanks for the heads up! I have updated to build from `docs`.

I think it's quite an achievement to be able to break things on first commit. 😄
