### ISSUE TITLE
Create management action modal

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#101]
Rather than including the management action fields in the observation form, create a **modal** that is separate from this form and which can be called by clicking `action` from:

- Table on zone management page
- Observation details

The modal should be the same for `create`, `edit` or `view` and will thus only have input fields. It has three buttons at the bottom:

- `Save`: save new or existing management action. Close modal
- `Cancel`: do nothing. Close modal
- `Delete`: ask for confirmation (extra modal?). If yes: delete and close modal. If no: stay at modal.

**Comment by niconoe** [comment]
@peterdesmet: is it acceptable if, when adding a new observation the flow is split in two pages:

- First page: user enter details about the nest
- Second page: success message + ability to open the modal to add action to the newly added nest
- (then, redirects as it is now)

This flow would keep code much simpler/robust because the modal is only able to add/delete/change actions to already existing (in the database) nests. 

What do you think, is it acceptable, at least for a first version? (I find it wiser to not add too much complex UI/frontend stuff before things have been stabilized and tested a bit more).

**Comment by peterdesmet** [comment]
That is fine! We can always revisit if we get feedback.

**Comment by niconoe** [comment]
Basic modal to add a management action from the table works. Next steps:
 
- [ ] Handle validation
- [ ] Handle deleting an existing action
- [ ] Handle editing an existing action
- [ ] Implements in various pages (when adding on obs, on details page, ...)

**Comment by bartaelterman** [comment]
@KarelSchoonvaere we discussed the option to allow firefighters to add multiple management actions to a nest. The alternative would be to have a single action, but a comment field where they can jot info from previous actions.
Do you have any feedback already about this? Which would be the preferred way of working?

**Comment by KarelSchoonvaere** [comment]
There is a meeting with the firefighters planned for 16th January. Tonight I am also seeing the person responsible so I can already ask him unofficially.

**Comment by niconoe** [comment]
Thanks. @bartaelterman : I have some comments from the technical side, always interested in your input. It feels in its current state the app is a bit in between...

- If we decide to indeed limit it to one, we should also enforce that at the model/validation level and make sure we have the correct DB representation for that.
- If we decide to allow multiple ones, we should make sure the whole site supports that, it seems some templates currently assume one.
- I still have this feeling that, if we decide to stick to one action per nest, this will change sooner than later (because in the "real world", it seems reasonable that multiple actions are performed on one signe nest). So if we can implement that in a way that's easy to change without breaking/refactoring the whole thing, it might be prudent :)

**Comment by bartaelterman** [comment]
Currently, the model allows for multiple, but on the templates, only the first one is returned (see here https://github.com/inbo/vespa-watch/blob/master/vespawatch/models.py#L435)
Since the form only allows you to create 1 and edit/delete that one if it already exists, you are as a user not really able to add multiple actions (except via the admin interface). I think that was a pragmatic compromise until things get clearer.
I agree with you, it's probably easier to first support multiple  actions and revert it back to 1 if need, then the other way round. Thant will require some changes to the templates indeed. One thing we discussed was - if we would go this way - that the table on the management page would be changed to a `ul` element of nests, each including a small table (or other list) with their actions.

**Comment by niconoe** [comment]
Basic edition is now working (still an issue with duration: minutes VS seconds)

**Comment by niconoe** [comment]
@peterdesmet : there's finally a decent add/edit/delete management action modal (accessible only from the management table for the moment, see screenshot below). Don't hesitate to test and give feedback!

![image](https://user-images.githubusercontent.com/386387/49724904-c4020600-fc6a-11e8-80b6-b4a07277a442.png)

**Comment by peterdesmet** [comment]
Needs to be tested. Note that actions can only be created. Edit + Delete is reserved for admin (see #333)

**Comment by peterdesmet** [comment]
This is now implemented
