### ISSUE TITLE
Email firezone for incoming validated nest observations

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#142]
An email notification should be send to the firezone user, when a new validated (#139) nest has been recorded in their zone.

**Comment by stijnvanhoey** [comment]
@berthuygens what would you advice (or is used in other applications): adding mailserver capabilities to the deployment (ec2 instances) or rather use the SES/SNS services from AWS and sent mails using these services?

In terms of infrastructure, the latter would require:
- an [SNS](https://aws.amazon.com/sns/) or [SES](https://aws.amazon.com/ses/) topic for the messaging
- subscriptions from the different firefighter zones with email (! need verification step)
- code-wise (@niconoe and @bartaelterman) use the SDK to post the message with an agreed filter to the SNS topic.

**Comment by niconoe** [comment]
From the app side, the nicest option would be to send the messages using the standard Django features (as opposed to manually importing another API in views).

It seems there exists (at least) a solution for that, [django-ses](https://github.com/django-ses/django-ses). I have no experience with it, but ready to try.

@stijnvanhoey (since I'm still a bit lost in the AWS terminology), SES is for sending mails and SNS for getting notifications (such as "e-mail was read")? Do we need both here or just the former?

**Comment by stijnvanhoey** [comment]
It is either SNS (notifications service with multiple types of _subscribers_ to the topics. A possible subscriber is receiving emails, but can be plugged with other processes as well) or SES (email specific service). 

According to @berthuygens the SES is preferred and has been used in _meetnetten_ as well (other django project)

**Comment by stijnvanhoey** [comment]
@niconoe how can I best try this out? if you provide me a location where I can add the `django.core.mail.send_mail` functionality or give me a small snippet, I can try it out myself both packages and the AWS settings.

**Comment by stijnvanhoey** [comment]
I added the policy document setup to the https://github.com/inbo/vespa-watch/tree/deployment-ses branch

**Comment by peterdesmet** [comment]
This is now superseded by #334
