### ISSUE TITLE
loading times, with main impact on points on map

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#157]
When loading the homepage, the time to have the observations/nest appear on the map is very long. When checking the flow:

![image](https://user-images.githubusercontent.com/754862/51749855-d1efd700-20b0-11e9-9ed4-de5cbf7aaf2e.png)

- loading of the static elements of the page (+/- 800ms)
- purple line is the loading of the carto background
- long waiting time is the api call `/api/observations`  => this inhibits the visualization of points in the map
- after 12 s -> loading off all observation images from the cache

The main issue is the ebsence of points on the maps during the `/api/observations` call.

**Comment by niconoe** [comment]
Indeed. I'm pretty sure a combination of three things will make that page load more decent:

- We'll improve the performances of the `/api/observations` call. Plenty of (not yet explored) options; nothing super easy/efficient since we've split Individuals and Nest in two tables and models, therefore some operations have now to be done in Python instead than at the DB level. I'll assign myself to solve this! 
- I suggest improving the map so it's obvious to the user that data is loading and the system is not stuck. It's a systemic fix that will also improve the user experience in other cases (such as poor connectivity)
- Hopefully the Amazon servers will have better performance than our laptops.

Sounds good?

**Comment by niconoe** [comment]
Performance is indeed terrible, worse than before. Will investigate immediately.

**Comment by stijnvanhoey** [comment]
The current dev server is indeed a small machine (`t2.micro`) and I don't think we need to solve performance here on the hardware side (vertical scaling). For a small application as this, it should be perfectly fine to run in production using a `t3.micro` (2 CPU instead of 1 in the `t2micro`) instance. As visitor levels will be very small in general, scaling for the occasional moment more users are active will be done horizontally using the autoscaling of elastic beanstalk.

(I did not used the django debug toolbar)

**Comment by niconoe** [comment]
After a bit of investigation, it seems most of the time is spent in the two `as_dict()`methods. In there, about half of the time is spent on getting the images (full size and thumbnails) URLs.

We're adding more and more fields to `to_dict()`, so this code can be reused in multiple pages. It's good, bit it may become incrementally slower because of that. I'm thinking of adding some parameters to make it lighter, when some part of the data is not needed (include_pictures=False, for example). 

That's also what iNaturalist does on its observations API. Will let it sink a bit and comes to that soon.

**Comment by niconoe** [comment]
This is interleaved/should be done in tandem with #152.

**Comment by niconoe** [comment]
Note to self: already improved things a bit while working on #152 / #184 thanks to `select_related()`. I should probably do something similar with pictures (`prefetch_realted()`?) in `get_observations()`.

**Comment by bartaelterman** [comment]
I made the following changes:

- We added a `light` parameter to the API. That returns fast, but incomplete, observation results. (by using django's `model_to_dict` builtin function).
- I've split the API. There is now an endpoint for nests and one for individuals.
- I've changed the way the popup was created. @peterdesmet  unfortunately It's now closer again to my first implementation, reverting some of your changes. Sorry for that, but there are two reasons for this:
    - the `light` API response does not include all information required for the popup. The map will now call the API for a single observation when the user clicks on a circle. This will now return all information we returned previously, but since it's only for a single observation, I expect this to be much faster.
    - by preventing to create all popups in advance and attaching them to the circle on click, we reduce the creation of lots of elements (and in particular, requesting all images) on page loading time. That could also improve the general performance.

I hope this makes the situation better. @stijnvanhoey can you also check how it's performing on AWS now?

These changes will probably have an impact on the management page. I've created #186 for this because the management page is not a prio right now.

Let me know what you think!

**Comment by stijnvanhoey** [comment]
This has certainly improved and the loading icon clarifies the loading. The popup-creation takes a bit longer now, but that's fine to me.

**Comment by stijnvanhoey** [comment]
When checking the loading of the map on firefighters level, the map keeps loading:

![image](https://user-images.githubusercontent.com/754862/53976063-8c3e1980-4106-11e9-8f04-495a2f2593d8.png)

**Comment by bartaelterman** [comment]
I was expecting some issues with the management map after this refactor. See #186 .
