### ISSUE TITLE
Additional steps during initial deployment

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#158]
When currently deploying the website the first time in a new environment, a lot of information is still missing to make the website work properly:
- without `identification_cards` the `add observation` won't work 
- i'm also thinking about the `page_fragments`

As we aim to have the environment completely re-deployable, we should have a procedure to provide the proper _defaults_ during initial deployment.

@niconoe should this be done with additional `manage.py` functionalities or do we have other options?

**Comment by niconoe** [comment]
The initial content can be created via a migration, so it nicely fits our existing procedure (we already do  this for the species table and page fragments - we'll just need better content for this).

Does that sounds like a good way to do it?

**Comment by stijnvanhoey** [comment]
> via a migration

Is that as part of the `python manage.py migrate --noinput` existing step?

**Comment by niconoe** [comment]
Yes.

**Comment by stijnvanhoey** [comment]
OK, and where is the content stored?

**Comment by niconoe** [comment]
The content appears in the migration files themselves. For example: https://github.com/inbo/vespa-watch/blob/1d3b5a5adfb787e170afb55b491b8f0309f02516/vespawatch/migrations/0002_initial_data.py#L8-L18

After the migration is applied, it's stored in the database. 

It makes sense from a Django viewpoint... Does it from yours and the AWS logic? Happy to explore other options if needed!

Note: the idea is replace the multiple messy migrations by a couple of clean ones (with better initial content for page fragments & co) just before the initial public release (after that, migrations will be added when necessary, but never removed/edited).

**Comment by stijnvanhoey** [comment]
Having the information inside the migration files itself makes sense, but how does this work on later deployments? Does the migrate functionality accounts for this?

**Comment by niconoe** [comment]
On later deployments, only the new migrations are applied since the database knows at which version it's at. So unless we manually create other migrations to hack existing content, it will not change automatically.

In other terms: except its initial populate operation via a migration, the Page Fragment data will be stored as regular application data in the database: it can be updated manually in the admin section and will never be changed again by a migration. Just like for the rest of the data (occurrences, management actions, ...), if you want to clone the website to another host, you have to dump and restore the database.

**Comment by stijnvanhoey** [comment]
closing here, further discussion on what to include in page fragments on initial setup to be discussed in #187
