### ISSUE TITLE
Detect current position doesn't work

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#169]
Does it work for anyone else?

**Comment by stijnvanhoey** [comment]
Nope.

**Comment by niconoe** [comment]
Hmmm, it seems to work for me. Any other message in the JS console?

**Comment by bartaelterman** [comment]
This seems to be browser dependent:
- Chrome (and Opera by the way 😛 ): browser first requests access to your location. If you approve, my OS now ask access to give the location to the browser. If approved again => location is set.
- Firefox: browser requests access. -> Approved -> veeeeery slow, but the location is set.
- Safari: nothing happens. Only a console warning saying `Access to geolocation was blocked over insecure connection to http://localhost:8000`. It could work when deployed on AWS. To be tested.

I'm not sure why Firefox is so slow. One thing we should take into consideration is that when a user has blocked access to his geolocation we probably get an error back that we should catch and give a message.

**Comment by niconoe** [comment]
Works fast for me in Firefox, and even located me in the right café :)

However, I just learned that the geolocation API is more and more restricted by browsers when the page is not accessed in HTTPS (with some exceptions for localhost). That would explain our different experiences. 

Opening another ticket to discuss the deployment over an HTTPS URL.

**Comment by niconoe** [comment]
Works for me in UAT now that HTTPS is in place (tested with recent Firefox, Chrome and Safari - in all cases the browsers asked the permission to share the location first.) Also seems to work fine from stock Android browser.

**Comment by peterdesmet** [comment]
Doesn't seem to work for me in production.

**Comment by stijnvanhoey** [comment]
Works for me in prd

**Comment by timadriaens** [comment]
Does not work on my samsung, cannot put placemark on the map and any location or city typed in consistently returns Hasselt as a placemark. probably need to try and solve this before launch & press release since journalists will try it on their phones.

**Comment by KarelSchoonvaere** [comment]
Works perfectly on my android at Bruges train station using chrome browser. Though there was an interactive message popping up asking me if I wanted to share my location which I accepted.

Btw: first citizen record of a Polistes wasp on the homepage! But link to iNaturalist is not working, so I am unable to navigate via the vespawatch website...

**Comment by mh-webops** [comment]
@KarelSchoonvaere I see the individual is marked as _To be synchronized_ which means there is no observation on iNaturalist yet. Could that be correct?
@timadriaens I also have a samsung. The first time I tried to record an observation, the app needed permission to access my location, I had to turn on my GPS, had to provide access again and when all that was done, nothing happened indeed. Having my GPS turned on now, I refreshed the page and now it worked. If you would experience similar behaviour, we might consider adding a message to tell them to refresh in case of a failure.
Also, the search still works right? So users have a way of registering their location anyway. Also dragging the pointer after a search works as expected.
Saying this because I have no idea what we could do otherwise to fix this issue.

**Comment by bartaelterman** [comment]
@KarelSchoonvaere I see the individual is marked as To be synchronized which means there is no observation on iNaturalist yet. Could that be correct?
@timadriaens I also have a samsung. The first time I tried to record an observation, the app needed permission to access my location, I had to turn on my GPS, had to provide access again and when all that was done, nothing happened indeed. Having my GPS turned on now, I refreshed the page and now it worked. If you would experience similar behaviour, we might consider adding a message to tell them to refresh in case of a failure.
Also, the search still works right? So users have a way of registering their location anyway. Also dragging the pointer after a search works as expected.
Saying this because I have no idea what we could do otherwise to fix this issue.

**Comment by stijnvanhoey** [comment]
I would indeed not pt additional implementation effort in the location-service, but providing documentation to the users on (1) supported OS/browsers and/or (2) gps-location on smartphone + refresh.

**Comment by peterdesmet** [comment]
Reported by @KarelSchoonvaere:

> When reporting an individual there's a problem with finding a query address.
When I neglect "Decteer huidige positie" but fill in "Zomergem" and click on "Zoek". Than the coordinates and pin on the chart are set to my current position and not to the coordinates of Zomergem. When I click "Zoek" a second time, then the coordinates of Zomergem are found and the pin is pointed at the correct location.
When I first click "Decteer huidige positie" and after fill in "Zomergem" and click on "Zoek", it also works perfect.
> 
> Seems to me the address look-up only works after the user's current position is known.

**Comment by bartaelterman** [comment]
The location detection is different now:
The site will immediately try to fill in the address field with the users current location (unless if the user did not give its browser permission to access his/her location). We'll need to test again to see if we keep this issue open.

**Comment by peterdesmet** [comment]
Seems location services were not enabled at system level for me: works now. Given that user can always search for location manually (which immediately stops location detection) I consider this issue solved.
