### ISSUE TITLE
Update observation form so species is already selected

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#170]
@niconoe, I'm splitting the work into the page before the individual/nest form (issue #168, almost done) and updates to the individual/nest form itself (this issue).

Basically, I would like that:

1. The selected taxon is passed to the form in a query string
2. The species form selector (and the code for it) is removed
3. The form has access to the `identification_card` properties, so I can display a form like this:

<img width="1135" alt="screenshot 2019-02-11 at 16 54 21" src="https://user-images.githubusercontent.com/600993/52575280-34213980-2e1e-11e9-8532-b60352bf2619.png">

**Comment by niconoe** [comment]
@peterdesmet : I'm about to remove the species selector, but I notice the same form was also used to edit existing observations. The selector was always shown, but sometimes (when the observation was taking its source in vespawatch, but the record was already pushed to inaturalist) in a read-only form. 

Since many things have changed, I have a few questions:

- Do we still need a form to change/update an observation in the frontend?
- If so, we'll need to review/define which fields can be edited, and under which conditions

If that's not needed for now, it might be simpler to remove all edition possibilities (in the frontend, there's still the admin) for now, and add them back in one form at a later stage, once we have a clearer perspective on all this.

**Comment by peterdesmet** [comment]
No, you can remove all editing possibilities. The only option you could leave in frontend is "delete".

**Comment by bartaelterman** [comment]
I updated the views. You should be able to access the identification card in the form template as `identif_card`
