### ISSUE TITLE
Indicate when map is loading

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#180]
We can use a Bootstrap spinner: https://getbootstrap.com/docs/4.3/components/spinners/

**Comment by niconoe** [comment]
Good idea! We'll need to update Bootstrap, since it doesn't appear to exist in the version we use (4.1.3). I guess it's a good idea to update anyway!

**Comment by bartaelterman** [comment]
Should put this on the play button because base map loads fast

**Comment by peterdesmet** [comment]
- [ ] Disable interaction with button when loading
- [ ] Set spinner on button when loading
- [ ] Set start date to 2015-06-01

Address #157 first

**Comment by niconoe** [comment]
Sorry, was working in parallel. I solved the initial point the simplest possible way. Finally use [Leaflet.Spin](https://github.com/makinacorpus/Leaflet.Spin) (much simpler than Bootstrap, due to our architecture).

**Comment by bartaelterman** [comment]
I thought it was going to be hard to put the spinner over the already loaded basemap, but it turned out that was not the case. Although the interaction is not really disabled, I think Nico's implementation is clear for now.
The start date is not set explicitly, but it is hidden as long as the data is not received from the API. Seems clean to me.
I'll close for now.
