### ISSUE TITLE
Check performance of the "see more observations" page

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#196]
See #157, which was also performance related.

**Comment by niconoe** [comment]
Had a quick look:

- Performance seems decent for me
- It uses the old, suboptimal `get_observation` call
- No obvious way to drastically improve performance* 

Given that, I'll let it open for a bit if anyone notice an issue please tell it. Otherwise I'll close this soon.


*options if we want to do it anyway:
- use some frontend code with infinite scroll to load them on the fly 
- make two pages, one for the latest nests and one for the lastest individuals some we are not impacted by the model split.)

**Comment by bartaelterman** [comment]
I committed db52a7295391966bb0ff81cdab5e278a60098cc1. See the commit messages. Closing this issue for now, but feel free to reopen if something's wrong / not ok.
