### ISSUE TITLE
Loading of static files is very slow

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#241]
I have the impression that loading static files on the production environment is very slow. After inspecting the network tab in my browser, I notice there is a difference between images and other static files (javascript files).
The images are clearly hosted on s3, they have locations like `https://lw-vespawatch-prd.s3.amazonaws.com/media/markdownx/599cf419-f155-4c86-8701-e605edd5ef3e.jpeg`.
The javascript files have addresses like `https://vespawatch.be/static/vespawatch/libraries/bootstrap/jquery.min.js` and they load terribly slow.
@stijnvanhoey how are static files from the django app deployed? Can we also put them on a s3 bucket? Maybe @niconoe can give some input here?

**Comment by stijnvanhoey** [comment]
@bartaelterman thanks for checking this. I can certainly adapt the setup to make sure the static files are hosted on AWS S3 as well.

**Comment by peterdesmet** [comment]
I'm getting a lot of timeouts on the website, so we should fix this soon.

**Comment by niconoe** [comment]
Hi again! Just a few comments:

- I encounter those speed issues/timeout, too.
- It would indeed be much better in production to load the static files from S3.
- That being said, I think there's another issue in this environment. Django is considered slow to serve static files but we shouldn't feel under a much higher load (10s to 100s of simultaneous users).

@stijnvanhoey / @berthuygens : To serve the static files from S3, the procedure should be very similar to what you already did with for Media files, they are handled almost the same by Django. Detailed instructions are in the [django-storages documentation](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html), but in a nutshell:
- set `STATICFILES_STORAGE` to `storages.backends.s3boto3.S3Boto3Storage`. (so Django know it needs to copy the static files to S3 during the deployment phase deployment)
- set `STATIC_URL` to the bucket URL. (Django will use this settings to generate static files URLs in HTML pages so the visitor's browser can access them)
- (configure a few more settings for the bucket name, permissions, ACL, ... but I suspect this is already mostly done thanks to your work on the media files).

Don't hesitate to ask for help, we are complementary since I know Django but not much about AWS :)

**Comment by stijnvanhoey** [comment]
@niconoe for the moment the website timeout issues are due to reverse proxy settings at INBO level and @berthuygens is checking this out.

**Comment by peterdesmet** [comment]
Addressed in #250 and much faster now.
