### ISSUE TITLE
Submitting form without info results in 500 error

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#244]
Submitting an empty nest or submission form results in:

> Server Error (500)

Expected: a warning on which fields are mandatory.

**Comment by bartaelterman** [comment]
I cannot reproduce this locally. There I get the expected behaviour. I'm wondering whether this is related to something you just mentioned: some fields are rendering very slow because loading static files is slow (#241). Maybe this only happens when you submit a form before all fields are loaded.
I'll see if we can catch that somehow, but the issue might be gone after resolving #241

**Comment by niconoe** [comment]
Cannot reproduce neither. @peterdesmet: if that happens locally, could you copy-paste the details of the error 500 (either from the error page, or from the Django runserver console)?

**Comment by peterdesmet** [comment]
Closing, probably related to AWS issues.
