### ISSUE TITLE
Corrected observation by iNaturalist community not updated

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#268]
We have currently on the homepage an observation (not vespa velutina):
![image](https://user-images.githubusercontent.com/754862/58081222-f66a4480-7bb4-11e9-8ba2-28114d8a6c81.png)

Although the community has corrected/changed the observation in the meanwhile:
![image](https://user-images.githubusercontent.com/754862/58081302-20236b80-7bb5-11e9-911f-579fee8483ef.png)

@bartaelterman and @peterdesmet is this an edge case we currently do not yet cover in the new sync operation? 

When I check, the observation (inat_id 25448547 and vw_id 187788): `HAS WARNINGS = TRUE` and running the sync again provides: `observation Individual 187788 was missing`, so not returned from iNaturalist. So, I assume things go wrong on 

https://github.com/inbo/vespa-watch/blob/c4da3aaddc73dd5c7324d65e8731aa8a80fe7f10/vespawatch/management/commands/inaturalist_sync.py#L82-L95

as in this case this should end in a delete from the vw database, no?

@KarelSchoonvaere and @timadriaens I do think it would be a bad idea to keep this (wrong) observation there when making the website public tomorrow? 

As the observation is from the Netherlands (but provided on our website), and it is on iNaturalist, I do think we can actually remove the observation from our database as a quick fix?

**Comment by timadriaens** [comment]
the observation is not yet set on research grade in Inaturalist because you need a species (not family level) for that. So isn't it normal that it can't be synced? I've suggested the species id. I think it need not be a problem necessarily for the launch, as the idea is also to stimulate contributors to join iNaturalist and help in identification. But for now, indeed, for the press release, I've removed it as suggested (it is kept on inaturalist anyway)

Having observations from abroad is good to promote use of the website and dataflow internationally so would keep it in (also, interesting to see border region observations in neighbouring countries). So for me: all is well.

**Comment by peterdesmet** [comment]
No @timadriaens deleting it removes it from iNaturalist as well. So that obs is now gone: https://www.inaturalist.org/observations/25448547 😕

Would be good to sit together to discuss management of all this. This is master data after all.

**Comment by KarelSchoonvaere** [comment]
To bad, was a nice species ( Cimbex femoratus) to have reported on iNat...



Op di 21 mei 2019 om 17:18 schreef Peter Desmet <notifications@github.com>:

**Comment by timadriaens** [comment]
is there no 'trash bin'? Someone ought to draw me a scheme of the flow of data between the site and iNaturalist and what happens when we edit/delete data on either side :-)

**Comment by bartaelterman** [comment]
Right, that's still on my to-do list :-\

**Comment by peterdesmet** [comment]
The original issue is resolved. I wouldn't invest time in creating a "trash bin" (there is one, but it is only accessible in the DB and will be emptied every hour on sync). I would however document the sync process: #285
