### ISSUE TITLE
No vue components in IE

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#283]
internet explorer does not display the map under 'location', nor the "date" field (see screenshot below)

![Vespa-Watch - Microsoft Internet Explorer wordt aangeboden door INBO_2019-04-09_21-22-48](https://user-images.githubusercontent.com/16116743/55828965-d6ebf080-5b0d-11e9-969e-52e32e11606d.jpg)

_Originally posted by @timadriaens in https://github.com/inbo/vespa-watch/issues/204#issuecomment-481401467_

**Comment by niconoe** [comment]
IE support seems doable, but as usual it might be long and painful. So we should decide if we want to do it, and which version to target (IE11 is enough I guess).

Another option is to throw a few hours at it and see how it goes before taking a hard decision.

**Comment by peterdesmet** [comment]
Not a lot of users have complained, so would drop this until it comes up a lot.

**Comment by KarelSchoonvaere** [comment]
Two users have complained, a third i'm not sure if it was related to IE. They were beekeepers. Since those are our first line observers but also an old race usually using old desktop computers with IE, I suppose we should do something. At least maybe have a pop-up message explaining them why IE is not compatible and what other options there are: like sending their message to vespawatch@inbo.be?
