### ISSUE TITLE
Validation process??

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#293]
I don't understand how the validation process works. Here an example:
- someone reports an "Asian hornet" but on the picture it is clearly an "European hornet"
- the iNat community is active and within a couple hours the observation gets 5 European hornet tags, which outweight the 1 Asian hornet tag (see picture). 

Currently this happens a lot on iNat, but the true "European hornet" tag never gets Research Grade label. As a result, the observation is not taken off the map on vespawatch.be.

How can corrected observations by the iNaturalist community obtain the Research Grade label?

![image](https://user-images.githubusercontent.com/26611593/58369139-a530bc80-7ef6-11e9-9728-944ecc54c1b6.png)

**Comment by peterdesmet** [comment]
Can you include the link to that obs?

**Comment by peterdesmet** [comment]
Ok, found it: https://www.inaturalist.org/observations/25523267

- That observation is identified as European hornet and has research level grade. 👌 You can see at the bottom of each observation on iNat - titled "data quality" - what is needed to get research level grade.
- The problem is that the map on vespawatch.be still shows it. That is a bug.

<img width="317" alt="Screenshot 2019-05-25 at 14 57 12" src="https://user-images.githubusercontent.com/600993/58369648-8aae1180-7efd-11e9-91c6-87b7fc3b0d14.png">

**Comment by KarelSchoonvaere** [comment]
Perfect! That's clear now. Thanks

**Comment by niconoe** [comment]
I was having a quick look at this but can't find the observation on our map anymore. Was that solved? This ticket and #276 seems to say it was **not**.

Can someone else reproduce the issue?

**Comment by bartaelterman** [comment]
I cannot reproduce this either. The observation mentioned above is not shown:
<img width="774" alt="Screenshot 2019-06-03 at 11 51 19" src="https://user-images.githubusercontent.com/2742677/58793208-f70fcb80-85f5-11e9-8532-2b67833729c6.png">

**Comment by bartaelterman** [comment]
Confirmed with @KarelSchoonvaere

**Comment by niconoe** [comment]
Probably due to an interrupted sync process (crash in the middle of step 4). In that case, that's finally recently fixed.
