### ISSUE TITLE
Add fields to users

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#324]
Info we need for users (to be added to database):

- [x] Username
- [x] Password
- [x] First name
- [x] Last name
- [x] Email address
- [x] Organization (company)
- [x] Description (of activities)
- [x] Telephone number
- [x] Notify me of new nests (boolean `email_notification`)

**Comment by bartaelterman** [comment]
We could create a custom `User` model with all these fields but we'd have to configure the app to make sure it uses this model instead of the default one (from the django.core.auth module). 
Another option is to use a `Profile` model with a one-to-one relation to a `User` model. The profile will contain all additional info and the user can change these himself. For updates on the user fields, (username, email address) the admin needs to be contacted.

I'm currently implementing it with a Profile model. Should be easy enough to switch to a full custom `User` model if needed.

**Comment by peterdesmet** [comment]
This is now implemented.
