### ISSUE TITLE
One time batch upload of observations

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#34]
@KarelSchoonvaere, let’s discuss here the upload of previously gathered observations to vespawatch: https://github.com/inbo/vespa-watch/issues/31#issuecomment-431896853. [Excel file](https://github.com/inbo/vespa-watch/files/2502287/inaturalist_uploads20181020.xlsx)

Some points to discuss:

1. Upload via vespawatch or iNat. Latter has a system to do so, but we would lose private fields such as observer email
2. Do you have photos?
3. What do you mean with consecutive observations for one observer?

**Comment by KarelSchoonvaere** [comment]
Most observations have photos. 

Consecutive observations are made by the same person on the same location. Here an example:
Beekeeper observes AH at his hive on 8/10/18: https://waarnemingen.be/waarneming/view/163329207
The next day he notices the hornet again: https://waarnemingen.be/waarneming/view/163363682

My custom database only takes the unique, first observation from the beekeeper and neglects all further observations until the nest is found. If necessary I can recover this information by going through my emails.

**Comment by peterdesmet** [comment]
Thanks!

1. I notice there is no private info in the spreadsheet, so we can upload via iNat. @niconoe @bartaelterman is there an issue in creating observations directly on iNat using the VespaWatch iNat account? In other words: do you use the VespaWatch user to identify obs created through the VespaWatch website, because that assumption will be false.

2. How can we retrieve them? I noticed you are not the observer for (all?) the observations. Do we have the right to upload those?
3. I'll let you decide if it's worth to look for those consecutive observations. I assume you _do_ create a separate observation for the nest, once found?

**Comment by Erytran** [comment]
1. you mean from the original observer? I can add this information quickly if you need it. My pictures still have to be added to the observations. That's why I intended to be the observer and upload through my iNats portal.
2. I assume we have permission, yes
3. Yes, nests are separate records each time

**Comment by KarelSchoonvaere** [comment]
That's me...

**Comment by peterdesmet** [comment]
@karelschoonvaere, are _your observations_ included in the spreadsheet? If so, I suggest you upload those on inat under your account first and remove them from the Excel. The rest we will upload via the vespawatch account.

If you can collect the photos for the others that would be great! For consistent naming, I suggest to give each observation an id, and name the images e.g. “23_2.jpg”: second picture for observation 23.

**Comment by KarelSchoonvaere** [comment]
Ok will look into this! Thanks for support.
What about future observations? More and more are coming in every week...

**Comment by peterdesmet** [comment]
Realistically speaking, application will be launched this winter. That should allow firestations and casual obs to report through website. For those collected on wn.be, we’ll have to see.

**Comment by niconoe** [comment]
What's the decision about this upload, finally? If possible for the sake of simplicity, let's try to keep those observations as normal as possible...

- In terms of synchronisation (see #2): does those observations behave like the ones originating from Vespa-Watch? In that case, I'd prefer that we add them to Vespa-Watch (but creating a CSV import tool is possible and maybe not too time-consuming)
- Or are there more behaving like the iNaturalist ones? In that case, let's push them to iNaturalist!

I don't mind much about the tools used (we can help develop what's needed), but I'd really like to keep the long term data models and synchronisation flows as simple and consistent as possible because those things can easily become fragile and messy :) )

@peterdesmet: to answer your question below: yes, the "pull" process currently considers an observation created under the Vespa-Watch account as originating from the Vespa-Watch webapp. Should that change? We could have 3 categories: regular observations from iNat VS vespa-watch observations from our app VS vespa-watch observations created on iNat via other means. But once again, I'll try to keep those things super simple as long as possible :)

**Comment by niconoe** [comment]
Fine for me, @KarelSchoonvaere can upload on iNat, using the Vespa-Watch account. Two remarks:

- I'll need to tweak the code that make the distinction between the obs from our app and the obs from iNaturatist. But that's not an issue, I already push a `vespawatch_id` observation field value to the observations from our app, so I can retrieve it later.
- More importantly, I wanted some reassurance that those observations will later (sync process) behave just like the regular iNaturalist observations (so we don't need to add a new code path, if possible... also for things like the non-standard metadata: nests, management actions, ...).

**Comment by peterdesmet** [comment]
The 140 obs are now uploaded: https://www.inaturalist.org/observations?place_id=any&subview=table&user_id=vespawatch&verifiable=any
