### ISSUE TITLE
Use of "reported by" for management actions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#346]
Management actions silently record the user that created them (see #332), but also have a field `person_name` translated as `Reported by`. Do we want to rename/reuse that field to record the organization / business that did the management action?

**Comment by KarelSchoonvaere** [comment]
The motivation for the field "Reported by" initially was to have the name of the person at the organization/business who conducted the management action in case we wan't to contact the people directly for questions or remarks.  For privat eradicators this is not relevant because they have 1 or a few people in service, But for firefighters this is necessary as wasp eradication teams can be very big. Thus, I would recommend not to reuse but keep both fields as separate values.

**Comment by peterdesmet** [comment]
Would it make sense to pre-populate the field with the registered user, or is it best to leave it empty?

**Comment by KarelSchoonvaere** [comment]
Not really. Fire figther account names are by zone while we need the name of the eradicator. This also accounts for privat companies. See my previous comment.

Perhaps the system can memorize the names so it can be selected from a dropdown that is specific to each account?

**Comment by peterdesmet** [comment]
Field should stay
