### ISSUE TITLE
what is the meaning of the warning "not in vespawatch project" ?

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#428]
The observation 88710317 shows the following error in the admin section: 

IndividualObservationWarning object (5891) | not in vespawatch project

What does this warning mean? It is also mentioned for a validated Vv by iNaturalist with iNaturlist ID 89503465 (https://vespawatch.be/admin/vespawatch/individual/195214/change/).

Thank your for your help.

![image](https://user-images.githubusercontent.com/35692395/128015699-f92183a1-ff10-4e7b-a4e2-49cea0627465.png)

**Comment by niconoe** [comment]
Thanks for the question @jrhillae:

First of all, this is a warning, not really an error: it's logged for traceability reasons (so it's good to check just like you did!), but most of the time it's not a problem in itself.

To answer your question: the warning means that when syncing an existing (in vespawatch) observation with iNaturalist, the system detected the observation is no longer part of the [vespa-watch iNaturalist project](https://www.inaturalist.org/projects/vespa-watch). This means the observation does not conform anymore with the [project needs](https://www.inaturalist.org/projects/vespa-watch?tab=about). It happens often because the identification has been fixed by the iNaturalist community and is no longer Vespa Velutina, but other criteria might have changed at the iNat side too (location outside of Belgium, date set before 2015, ...). Sometimes the warning is also transient (because the identification is disputed, for example) and the warning was recorded at some point, but not on more recent sync operations).

Hope this helps understanding the system. Feel always free to ask to check if a specific instance of this warning is indeed normal!

**Comment by jrhillae** [comment]
Now it is clear to me. Thank you for your answer :).
