### ISSUE TITLE
Automatically add zone to observation

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#48]
Observations without a `vespawatch_zone` should be assigned one automatically based on the coordinates (and the polygon of the zone they fall into).

Once an observation has a `vespawatch_zone` this is never overwritten automatically, but only directly by a user.

**Comment by bartaelterman** [comment]
Depends on #46

**Comment by niconoe** [comment]
This is now implemented. It works like this: if an observation has no zone assigned it tries to set on each time the model is saved (so it works consistently from scripts, user-facing pages, admin...).

The only limitation I see with this approach is that you can't set the zone to NULL if an observation falls in it (you can of course set it to a different zone). In other terms, all observations will have a zone, either set manually or automatically.  The only exception is the case where the auto assignment fails, because the point doesn't fall into any zone (non-Flemish observations). Is that acceptable?

**Comment by peterdesmet** [comment]
Yes, so the only obs with a NULL zone will be those outside any zone. Question: is this zone set for all obs (independent from nest or individual)?

**Comment by peterdesmet** [comment]
Yes.
