### ISSUE TITLE
Improvements to map

### ISSUE THREAD

**Issue by PietrH** [inbo/vespa-watch#486]
The form request browser location permissions, when you refuse, you can't use the map or fill in coordinates manually. Thus blocking you from filling in the form. 

If you do give location permission, there is a delay, and you can drag and move the placed pin, this might be confusing for some users without a pointer that they are allowed to move the pin

**Comment by peterdesmet** [comment]
- [ ] Allow users to place a marker when location services are not turned on (currently they get [an error](https://user-images.githubusercontent.com/600993/230576528-2d25cfa1-0e05-4fde-a14d-5b5574eea6de.png)).
- [ ] Add a help text:

```html
<div class="close-button d-flex justify-content-between align-items-center my-2">
  <span class="small">Duid de locatie van het nest aan op de kaart. De markering kan verplaatst worden.</span>
  <button class="btn btn-danger" type="button" data-dashlane-rid="493bf3da44de56a2" data-form-type="other" data-dashlane-label="true">X</button>
</div>
```

<img width="641" alt="Screenshot 2023-04-07 at 10 51 10" src="https://user-images.githubusercontent.com/600993/230577122-28dad3c5-947e-4f5e-9c67-79c60cb7d74c.png">

- [ ] Allow users to switch between map and satellite view. I consider this more important than being able to have the map full screen, so that basemap selector button could be placed in the top right corner
- [ ] Zoom in further on the map (maybe this will be solved by adding the Google Maps API key)

**Comment by peterdesmet** [comment]
Help text added
