### ISSUE TITLE
JS error in nest form

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#534]
The nest form at https://github.com/inbo/vespa-watch/commit/15f8e06343cbaa82cfb02832c92f07ea925e23a8 returns:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'SearchBox')
    at getLocation (iasset.js:60:61)
    at HTMLInputElement.<anonymous> (iasset.js:351:21)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

And does not function.

**Comment by peterdesmet** [comment]
I made a hard reset to 94c61ac and the form functions again. The PR with the address box should be resubmitted.

**Comment by SanneVanDonink** [comment]
Peter Petrov: The issue is with the google places API. 

Can you check if it is enabled, you can find more information at the following URL  - https://developers.google.com/maps/documentation/javascript/places

Also, can you add the following param (&libraries=places) at the end of the script - <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&key=&libraries=places"></script>

@peterdesmet can you look into this? Thanks in advance!

**Comment by peterdesmet** [comment]
This has been resolved in:

- https://github.com/inbo/vespa-watch/commit/12a9e66639f9ea55b068af2e9b994fce3fec52ec: enable `places` library
- https://github.com/inbo/vespa-watch/commit/4269eab1268dd6bd257b555375ce8fedc31ec8fb: add code originally submitted as #532
https://github.com/inbo/vespa-watch/commit/fe00431584666268f83a98be264c3999a77d25bf: fix some div placement issues that caused the Google Maps div to be hidden
