### ISSUE TITLE
Write import script that creates Firefighters zones from the provided shapefile

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#61]
Prerequisite for #48, follow up of #46.

Should we also integrate #28?

**Comment by niconoe** [comment]
@stijnvanhoey : can you adapt the deployment script so:

$ python manage.py import_firefighters_zones PATH_TO_VESPAWATCH/data/Brandweerzones_2019_simplified/Brandweerzones_2019_simplified.shp

is run once, at initial deployment?

**Comment by stijnvanhoey** [comment]
I would argue to use a geojson file instead of a json-file as input for the command. It is text and as such relevant under version control, it is a single file instead of combination of files. Moreover, it is rendered interactively in Github. 

So, I would:
- consider the shapefile -> geojson conversion outside of the application. 
- Use ogr2ogr command `ogr2ogr -f GeoJSON -t_srs [crs] [name].geojson [name].shp ` for the conversion as well as the simplification and document this in readme.md
- commit and vc the geojson file
- I'll add the import command to the deployment `python manage.py import_firefighters_zones PATH_TO_VESPAWATCH/data/Brandweerzones_2019_simplified/brandweerzones_2019.geojson`

**Comment by niconoe** [comment]
Thanks for the review @stijnvanhoey, that's adapted.

I choose to not simplify the features at this time because:

- even if the initial file is around 4Mb, that's a perfectly fine amount of data for PostGIS/GeoDjango. Premature optimization is the root of all evil ;)
- it's not that easy to exactly quantify the error we're adding while simplifying geometries, in part we configure the tolerance in degrees (which have a different impact depending of the axis and feature position) in part because GeoJSON is a text format, so we need to not only simplify but also lessen the number of decimals if we want to see a substantial impact on the file size.

**Comment by stijnvanhoey** [comment]
Tried it in the deployment, but need further checke, opening for myself.

**Comment by stijnvanhoey** [comment]
By providing the ssh command (or logging into a machine after initial setup), the command can be executed as required. Documentation is added, need to be checked in the bash instructions file.

**Comment by stijnvanhoey** [comment]
works fine during deployment and documented, closing.
