### ISSUE TITLE
vespawatch_evidence for "beehive"

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#70]
@KarelSchoonvaere in your upload (#34) there are `nest`, `individual` and `beehive`. The first two have been mapped as such to `vespawatch_evidence`, but what should be done for `beehive` observations?

https://www.inaturalist.org/observations?place_id=any&q=beehive&subview=table&user_id=vespawatch&verifiable=any

Are these all `vespawatch_evidence`: `individual`?

How should the fact that these were observed near beehives be recorded?

**Comment by bartaelterman** [comment]
I think we would record those as individuals with behaviour 'at beehive'

**Comment by KarelSchoonvaere** [comment]
In the vespawatch preparing template there is the option for people to tick whether they are beekeeper or not. That information is crucial because we expect many reports from beekeepers and will notify the beekeepers society in that region when reports come in. 

Reports at beehive are in fact individuals, so there is no need for a separate category. Ideally would be to distinguish loose and beehive observations by color code on the map or by different layers

**Comment by stijnvanhoey** [comment]
in the current setup, there is:
- defining the observation is provided by a beekeeper (this does not inherently says this observation is at a beehive)
- defining the behavior *hunting at hive*, which is saying the observation is at the hive

So, how would these be mapped?

**Comment by peterdesmet** [comment]
Decided: keep current implementation “hunting at beehive” in behaviour.
