### ISSUE TITLE
Create single messages template snippet

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#90]
@bartaelterman can you review which templates actually need messages? It seems odd to have it e.g. on the homepage:

https://github.com/inbo/vespa-watch/blob/c92357b46e18df5d6bb1f44aba37e53306238dda/vespawatch/templates/vespawatch/index.html#L20-L31

And if multiple templates require the same code block for messages, I would create a snippet for that in an `templates/includes` folder, cf. https://github.com/tdwg/tdwg-theme/tree/master/templates/includes

**Comment by bartaelterman** [comment]
When you create a new observation by clicking on the "new observation" button on the homepage, you are redirected to the homepage if the creation succeeds. In that case, a message is displayed by this snippet to say that your observation was successfully created. (Implemented in #38 )

The same piece of code is also used on the management page because that is where you are redirected to when you clicked the "new observation" button there. A single snippet would for both templates would indeed be useful.

Changing the title of this issue.

**Comment by niconoe** [comment]
Another common way to solve this (and allows messages on all pages) is to add this code in the base template, before the actual content is inserted by the real templates (not sure if that applies here).

**Comment by peterdesmet** [comment]
For now I only encountered it on the management and index page, so just including it there. Also for styling it's easier to NOT include it in base.html

**Comment by peterdesmet** [comment]
Closing
