### ISSUE TITLE
Only pull Vespa velutina (and subspecies) from iNat

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#93]
The sync with iNaturalist should only pull Vespa velutina from iNaturalist.

**Comment by niconoe** [comment]
@peterdesmet : what is the end goal there? Not having them cluttering the map?

I'm asking because if we just don't pull them from iNat, we have to make sure that doesn't break in any way the sync process described in detail in #2 (I'm thinking the edge cases, for example where we send them to iNat as V. velutina, but the community says it's in fact V. crabro, and we have some obs in our database that are not retrieved on the next pull, ...).

Some possible solutions:

- Review each combination of edge case to make sure we don't break the sync.
- Mitigate the issue by only applying this filtering to the observations that do *not* originate from our website (still need to look further to make sure we don't break anything).
- Keep the sync process as it is, and filter the observations as we display them.

**Comment by peterdesmet** [comment]
Good points. I would not remove any obs from our database, as the system could be gamed. E.g. we don’t want to loose related management actions because iNat users suddenly decide to mark all our obs as not Vespa velutina.

Filtering is probably the simplist solution for now. And yes, it is about clutter. I.e. showing the recorded distribution of the target species.

**Comment by niconoe** [comment]
Filtering (at display time) will be implemented. 

Your first point (not remove any obs from our database) will have to be discussed again, since it has implications with #2 (where we have some edge cases where deletion occur) and since  it seems to answer "yes" to #126 (so more work will be needed there).

**Comment by niconoe** [comment]
If we're finally revamping the sync mechanism a bit more in depth, it may makes sense to reconsider this issue: maybe it's actually better to only pull V. Velutina...

**Comment by peterdesmet** [comment]
See #2: we will only pull V. velutina.

**Comment by bartaelterman** [comment]
Looks like an old issue that can be closed now
