### ISSUE TITLE
Investigate file per vue component

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#97]
Check documentation on how vue components can be defined per file and compiled for production, rather than having everything in vespawatch.js. Is this easy to setup?

**Comment by bartaelterman** [comment]
Listing some ideas and resources here:

- This is where we should get started: https://vuejs.org/v2/guide/single-file-components.html
- We should probably go for a bundler like webpack or browserify. From a first glance, webpack seems very well documented and I have the impression from the vue docs that that is the preferred one. It also seems to be the default when you use the vue CLI (see my last point). Here is a gitbook that documents a [template project set up with vue and webpack](https://vuejs-templates.github.io/webpack/).
- The main concepts of webpack are documented [here](https://webpack.js.org/concepts/). The idea seems straightforward: webpack will search for files (be default, only `.js`) and bundle them to some output place. You can configure the [vue loader](https://vue-loader.vuejs.org/#what-is-vue-loader) in your webpack config to detect `.vue` files and unpack the different blocks in them. After that step, you can add additional steps to bundle the js, templates or styles from the SFCs. (single file components)
- We have to make sure that the bundled output is correctly loaded into the html. Webpack has a [HTMLWebpackPlugin](https://webpack.js.org/guides/output-management/#setting-up-htmlwebpackplugin) that rewrites your index.html with the correct imports.
- Vue-loader/Webpack has a [hot reload feature](https://vue-loader.vuejs.org/guide/hot-reload.html#state-preservation-rules). This seems very useful for development, but how do we integrate that with our django server? The vue webpack template project has a page about [integrating with a backend framework](https://vuejs-templates.github.io/webpack/backend.html). [This blogpost](https://ariera.github.io/2017/09/26/django-webpack-vue-js-setting-up-a-new-project-that-s-easy-to-develop-and-deploy-part-1.html) describes a way to set up a similar project. And make sure to check out plugins such as [django-webpack-loader](https://github.com/owais/django-webpack-loader) and [webpack-bundle-tracker](https://github.com/owais/webpack-bundle-tracker). 
- Vuejs has a [CLI for bootstrapping an app with webpack](https://cli.vuejs.org). That will make it way easier to get everything set up. I think it makes sense to start fresh with the CLI and copy all our components into this new app. Alternatively, we can configure everything manually, but since the complete bundling involves a couple of steps, I'm afraid we will get lost in connecting the dots.

**Comment by niconoe** [comment]
Thanks @bartaelterman, great list, that match quite well what I also found.

Honestly, I don't think it's the right time to implement this: from my experience, it will add a ton of complexity because we'll end up adding tools none of us is really familiar with and which will have many interactions (webpack/bundler + npm + django templates + some django plugins to glue all this together, at least), and this will also have costs in terms of deployment.

Generally speaking, I believe it's the kind of stuff that should be implemented only when it hurts/slow people down to not have them (when the project is much bigger, for example), not at an early stage for reasons such as "it's a bit nicer to have everything in the same file" or "that's what all the cool kids are doing".  I'm not against doing it *when the need clearly arises*.

Also, don't hesitate to disagree!

**Comment by bartaelterman** [comment]
I totally agree! With the list I compiled now it makes it clear that this is not something we'll be able to do in a day. @peterdesmet up to you to move this issue down in the priorities list if you think that's appropriate.

**Comment by peterdesmet** [comment]
Thanks for the research. Indeed not something to tackle right now.

**Comment by peterdesmet** [comment]
@bartaelterman I guess we will never implement this and stick with a single `vespawatch.js`

**Comment by niconoe** [comment]
I'd say it's the right approach for now. Should I close this one?
